### ISSUE TITLE
Need to update DAT zoom setting

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jdat#37]
Staging had zoom setting at 1.0 which was causing text templates to produce fonts that were too small for their set size. Mike and I tested it and he found the 1.6 setting most closely matches expected font sizes in PDFs. 

need to update the zoom setting to 1.6 in all environments and restart

**Comment by tobiasnteireho** [comment]
"WKHTMLTOPDF_DPI": 300,
  "WKHTMLTOPDF_ZOOM": 1.000

has been the linux setting for a while what changed?

**Comment by tobiasnteireho** [comment]
I measured by pixel to get ratios from below

![image (2)](https://user-images.githubusercontent.com/23437466/106528850-15a32580-64af-11eb-961d-c4cb80d9fe2e.png)

 It looks like the zoom wants to be ~1.570909090909091 which is pretty close to 1.6.... so I'm not sure what changed so that linux and windows need identical zoom

**Comment by tobiasnteireho** [comment]
Measuring pixel by pixel on linux the zoom now should be

1.6711

So the linux now needs a ~6% higher zoom than azure when previous versions required a 28% higher zoom on azure vs linux

**Comment by tobiasnteireho** [comment]
updated in current docs with cal toolkit
